### ISSUE TITLE
Seems like incomplete installation - missing python script.

### ISSUE THREAD

**Issue by matthiasfromm** [Ultraschall/Reaper-Plugin#6]
Hi guys!

I installed Ultraschall 1.2.2 today (over an older installation of 1.1.).

After I restarted Reaper I noticed that in the top left corner it still says "Ultraschall 1.1".

Additionally, when I wanted to set a edit marker (using "E") it didn't work. Instead, I received an error message from "ReaScript Output" saying "Can't load file:  /Users/fromm/Library/Application Support/REAPER/Scripts/ultraschall_set_edit.py".

![image](https://cloud.githubusercontent.com/assets/2086207/5790000/26f9153e-9e85-11e4-9474-86d175ce992c.png)

I am working on Mac OS X 10.9.5 with Reaper v4.76/64 rev 0047d7.

Any idea? Can I just past the missing ultraschall_set_edit.py to the folder?

Thanks for your support!

Cheers,
Matthias

**Comment by heikopanjas** [comment]
Hi Matthias, 

this seems to be exactly the same issue another user had 1 or 2  weeks ago. Please clear your browser cache and download the installer package again. After that, please run the downloaded installer and reapply the 'Ultraschall_1.2.ReaperConfigZip' file by dragging it to the REAPER application window. If that doesn't help, please tell me so we can a deeper look into the problem.

Kind regards,
Heiko

**Comment by matthiasfromm** [comment]
That solved the problem! Thanks Heiko!
